### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by goodbomb** [lynndylanhurley/redux-auth#53]
Hi, I'm getting the following error when attempting to install this module.

```
npm info postinstall redux-auth@0.0.2
npm WARN unmet dependency C:\Users\bescott\Work\QE\viu-fe\node_modules\redux-auth\node_modules\redux-router\node_modules\history requires query-string@'^3.0.0' but will load npm WARN unmet dependency C:\Users\bescott\Work\QE\viu-fe\node_modules\redux-auth\node_modules\query-string,
npm WARN unmet dependency which is version 2.4.2
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "redux-auth" "--save"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bescott\Work\QE\viu-fe\npm-debug.log
```

**Comment by Aleyasen** [comment]
I am getting the same!

npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN peerDependencies The peer dependency history@^1.17.0 included from react-router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
|
> react-router@1.0.3 postinstall H:\workspace\DarshanVis-UI\node_modules\redux-auth\node_modules\react-router
> node ./npm-scripts/postinstall.js

npm WARN unmet dependency H:\workspace\DarshanVis-UI\node_modules\redux-auth\node_modules\redux-router\node_modules\history requires query-string@'^3.0.0' but will load
npm WARN unmet dependency H:\workspace\DarshanVis-UI\node_modules\redux-auth\node_modules\query-string,
npm WARN unmet dependency which is version 2.4.2
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "redux-auth" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0

npm ERR! Please include the following file with any support request:
npm ERR!     H:\workspace\DarshanVis-UI\npm-debug.log

**Comment by alinseba** [comment]
Same here.

`> react-router@1.0.3 postinstall /home/butifanu/Desktop/jobs/node_modules/redux-auth/node_modules/react-router
> node ./npm-scripts/postinstall.js

npm WARN unmet dependency /home/butifanu/Desktop/jobs/node_modules/redux-auth/node_modules/redux-router/node_modules/history requires query-string@'^3.0.0' but will load
npm WARN unmet dependency /home/butifanu/Desktop/jobs/node_modules/redux-auth/node_modules/query-string,
npm WARN unmet dependency which is version 2.4.2
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "redux-auth" "--save"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0
`

**Comment by brajt** [comment]
Same thing here.

```
11371 warn unmet dependency /home/ubuntu/workspace/sunny/demo/client/node_modules/redux-auth/node_modules/redux-router/node_modules/history requires query-string@'^3.0.0' but will load
11371 warn unmet dependency /home/ubuntu/workspace/sunny/demo/client/node_modules/redux-auth/node_modules/query-string,
11371 warn unmet dependency which is version 2.4.2
11372 verbose stack Error: The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!
11372 verbose stack     at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/lib/install.js:125:32
11372 verbose stack     at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/lib/install.js:268:7
11372 verbose stack     at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
11372 verbose stack     at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
11372 verbose stack     at cb (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
11372 verbose stack     at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
11372 verbose stack     at cb (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
11372 verbose stack     at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
11372 verbose stack     at cb (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
11372 verbose stack     at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
11373 verbose cwd /home/ubuntu/workspace/sunny/demo/client
11374 error Linux 4.2.0-c9
11375 error argv "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.3/bin/npm" "install" "redux-auth" "--save"
11376 error node v4.4.3
11377 error npm  v2.15.1
11378 error code EPEERINVALID
11379 error peerinvalid The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!
11379 error peerinvalid Peer react-router@1.0.3 wants history@^1.17.0
11380 verbose exit [ 1, true ]
```

**Comment by jasongonzales23** [comment]
+1

**Comment by lynndylanhurley** [comment]
Please try again with `v0.0.4`

**Comment by lynndylanhurley** [comment]
Should be fixed in the latest release.

**Comment by youalreadydid** [comment]
Still an issue with 0.0.5-beta5
`├── UNMET PEER DEPENDENCY react-router-bootstrap@*`

**Comment by marekciupak** [comment]
I had the same problem. Manual installation of the package fixed the problem for me: `npm install react-router-bootstrap --save`.
